//===--- Store.swift ------------------------------------------------------===//
//
// This source file is part of the swift-library open source project
//
// Created by Xudong Xu on 4/5/23.
//
// Copyright (c) 2023 Xudong Xu <showxdxu@gmail.com> and the swift-library project authors
//
// See https://swift-library.github.io/LICENSE.txt for license information
// See https://swift-library.github.io/CONTRIBUTORS.txt for the list of swift-library project authors
// See https://github.com/swift-library for the list of swift-library projects
// See https://redux.js.org for redux documentation
//
//===----------------------------------------------------------------------===//

import class Foundation.NSRecursiveLock

/// This class is the default implementation of the `StoreType` protocol. You will use this store in most
/// of your applications. You shouldn't need to implement your own store.
/// You initialize the store with a reducer and an initial application state. If your app has multiple
/// reducers, combine them into one `Reducer` function that calls each of them.
///
/// A store is safe to use from several threads. Dispatching, subscribing and unsubscribing are serialized
/// by a recursive lock, so a dispatch from another thread waits until the current one finishes, while
/// middleware and listeners can dispatch again on the same thread. Listeners run while the store holds
/// that lock, so a listener must not block on another thread that uses the same store.
open class Store<State>: StoreType, @unchecked Sendable {

  public var middleware: [Middleware<State>] {
    get { withLock { _middleware } }
    set {
      withLock {
        _middleware = newValue
        _underlyingDispatch = underlyingDispatch()
      }
    }
  }

  /// The current state of the store.
  public var state: State! {
    withLock { _state }
  }

  private let lock = NSRecursiveLock()

  private var reducer: Reducer<State>

  private var _middleware: [Middleware<State>]

  private var _state: State! {
    didSet {
      sinks.forEach {
        $0.forward(oldValue, newValue: _state)
      }
    }
  }

  private lazy var _underlyingDispatch: DispatchAction = underlyingDispatch()

  private var sinks: Set<Sink<State>> = []

  private var isReducing = false

  /// Create store with reducer, initial state and middlewares.
  ///
  /// - Parameters:
  ///   - state: Initial state, if any. If `nil` is set, state will be generated by reducer function.
  ///   - reducer: a pure function to modify state with action.
  ///   - middleware: list of middleware to process side effect logic, dispatched before reducer.
  public required init(
    state: State?, reducer:
    @escaping Reducer<State>,
    middleware: [Middleware<State>] = []
  ) {
    self.reducer = reducer
    self._middleware = middleware

    if let state = state {
      self._state = state
    } else {
      dispatch(BuiltInAction.initialize)
    }
  }

  /// Dispatch action to middlewares, reducer and update state
  /// - Parameter action: action to dispatch
  open func dispatch(_ action: ActionType) {
    withLock {
      _underlyingDispatch(action)
    }
  }

  /// Dispatch action to reducer and update state
  ///
  /// A reducer must not dispatch actions: an action that arrives while the reducer is running stops the program.
  /// - Parameter action: action to dispatch
  open func _dispatch(_ action: ActionType) {
    withLock {
      guard !isReducing else {
        fatalError(
          """
          Reducers may not dispatch actions. Store received \(action) while its reducer was running.
          """)
      }

      isReducing = true
      let newState = reducer(action, _state)
      isReducing = false

      _state = newState
    }
  }

  public func subscribe(_ listener: @escaping (State) -> Void) -> Unsubscribe {
    let sink = Sink(observer: {
      listener($1)
    })
    return subscribe(sink)
  }

  public func subscribe<Substate>(
    _ listener: @escaping (Substate) -> Void,
    selector: @escaping Selector<State, Substate>) -> Unsubscribe
  {
    let sink = Sink<State>(observer: {
      listener(selector($1))
    })
    return subscribe(sink)
  }

  private func subscribe(_ sink: Sink<State>) -> Unsubscribe {
    withLock {
      _state.flatMap {
        sink.forward(nil, newValue: $0)
      }
      sinks.update(with: sink)
    }

    return { [weak self] in
      guard let self else {
        sink.cancel()
        return
      }
      self.withLock {
        sink.cancel()
        _ = self.sinks.remove(sink)
      }
    }
  }

  private func withLock<Result>(_ body: () throws -> Result) rethrows -> Result {
    lock.lock()
    defer { lock.unlock() }
    return try body()
  }

  /// Create dispatch action chain for middlewares and reducer
  ///
  /// - Returns: an dispatch action chain with closure type
  private func underlyingDispatch() -> DispatchAction {
    return _middleware
      .reversed()
      .reduce({ [unowned self] action in
        self._dispatch(action)
      }, { [weak self] nextDispatch, middleware in
        middleware({ [weak self] in self?.state })({ [weak self] in self?.dispatch($0) })(nextDispatch)
      })
  }
}
